apiVersion: multicluster.orange.com/v1alpha1
kind: CassandraMultiCluster
metadata:
  name: cassandramulticluster-demo
spec:
  # Add fields here
  base:
    apiVersion: "db.orange.com/v1alpha1"
    kind: "CassandraCluster"
    metadata:
      name: cassandra-demo
      namespace: cassandra-demo
      labels:
        cluster: casskop
    spec:
      baseImage: orangeopensource/cassandra-image
      version: latest-cqlsh
      #configMapName: cassandra-configmap-v1
      #dataCapacity: "20Gi"
      #dataStorageClass: "standard-wait"
      imagepullpolicy: IfNotPresent
      checkStatefulsetsAreEqual: true
      hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
      deletePVC: true
      autoPilot: false
      gcStdout: false
      autoUpdateSeedList: false
      maxPodUnavailable: 1
      nodesPerRacks: 1
      runAsUser: 1000
      resources:         
        requests:
          cpu: '0.3'
          memory: 2Gi
        limits:
          cpu: '0.3'
          memory: 2Gi
  override:
    gke_dfy-bac-a-sable_europe-west1-b_istio1:
      metadata:
        name: cassandra-demo1
        namespace: cassandra-demo
      spec:
        topology:
          dc:
            - name: dc1
              nodesPerRacks: 1
              numTokens: 256
              rack:
                - name: rack1
                - name: rack2
    gke_dfy-bac-a-sable_us-central1-a_istio2:
      metadata:
        name: cassandra-demo2
        namespace: cassandra-demo
      spec:
        topology:
          dc:
            - name: dc2
              nodesPerRacks: 1
              numTokens: 256
              rack:
                - name: rack3
                - name: rack4
      
  
