apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandramulticlusters.multicluster.orange.com
spec:
  group: multicluster.orange.com
  names:
    kind: CassandraMultiCluster
    listKind: CassandraMultiClusterList
    plural: cassandramulticlusters
    singular: cassandramulticluster
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
