apiVersion: multicluster.orange.com/v1alpha1
kind: CassandraMultiCluster
metadata:
  name: cassandramulticluster-demo
spec:
  # Add fields here
  base:
    apiVersion: "db.orange.com/v1alpha1"
    kind: "CassandraCluster"
    metadata:
      name: cassandra-demo
      namespace: default
      labels:
        cluster: casskop
    spec:
#      baseImage: orangeopensource/cassandra-image
#      version: latest-cqlsh
      baseImage: allamand/cassandra-image
      version: 3.11.4-8u212-0.3.1 
      configMapName: cassandra-configmap-pre-run
      dataCapacity: "20Gi"
      dataStorageClass: "standard-wait"
      imagepullpolicy: IfNotPresent
      checkStatefulsetsAreEqual: true
      hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
      deletePVC: true
      autoPilot: false
      gcStdout: false
      autoUpdateSeedList: false
      maxPodUnavailable: 1
      nodesPerRacks: 1
      runAsUser: 1000
      resources:         
        requests:
          cpu: '2'
          memory: 4Gi
        limits:
          cpu: '2'
          memory: 4Gi
    status:
      seedlist:
        - cassandra-0.cassandra
        - cassandra-1.cassandra
  override:
    gke_dfy-bac-a-sable_europe-west1-b_istio1:
      metadata:
        name: cassandra-demo1
        namespace: default
      spec:
        topology:
          dc:
            - name: dc1
              nodesPerRacks: 1
              numTokens: 256
              rack:
                - name: rack1
                - name: rack2
    gke_dfy-bac-a-sable_us-central1-a_istio2:
      metadata:
        name: cassandra-demo1
        namespace: default
      spec:
        topology:
          dc:
            - name: dc2
              nodesPerRacks: 2
              numTokens: 256
              rack:
                - name: rack3
                - name: rack4
        resources:         
          requests:
            cpu: '2'
            memory: 4Gi
          limits:
            cpu: '2'
            memory: 4Gi
      status:
        seedlist:
          - 10.20.3.5


  
