// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	dbv1alpha1 "github.com/Orange-OpenSource/cassandra-k8s-operator/pkg/apis/db/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraMultiCluster) DeepCopyInto(out *CassandraMultiCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraMultiCluster.
func (in *CassandraMultiCluster) DeepCopy() *CassandraMultiCluster {
	if in == nil {
		return nil
	}
	out := new(CassandraMultiCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraMultiCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraMultiClusterList) DeepCopyInto(out *CassandraMultiClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CassandraMultiCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraMultiClusterList.
func (in *CassandraMultiClusterList) DeepCopy() *CassandraMultiClusterList {
	if in == nil {
		return nil
	}
	out := new(CassandraMultiClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraMultiClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraMultiClusterSpec) DeepCopyInto(out *CassandraMultiClusterSpec) {
	*out = *in
	if in.CassandraCluster != nil {
		in, out := &in.CassandraCluster, &out.CassandraCluster
		*out = make([]dbv1alpha1.CassandraCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraMultiClusterSpec.
func (in *CassandraMultiClusterSpec) DeepCopy() *CassandraMultiClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CassandraMultiClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraMultiClusterStatus) DeepCopyInto(out *CassandraMultiClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraMultiClusterStatus.
func (in *CassandraMultiClusterStatus) DeepCopy() *CassandraMultiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CassandraMultiClusterStatus)
	in.DeepCopyInto(out)
	return out
}
